FROM python:3.8
RUN apt-get clean -y && apt-get update -y && apt-get install bash
RUN pip install --upgrade pip 
#EXPOSE 8080
EXPOSE 5000       
#COPY . /app
COPY ./main.py /app/main.py
COPY ./streamlit_app.py /app/streamlit_app.py
COPY ./requirements.txt /app/requirements.txt
COPY ./src /app/src
COPY ./.streamlit /app/.streamlit
WORKDIR /app
RUN pip install -r requirements.txt
#CMD [ "streamlit", "run", "streamlit_app.py", "--server.port=8080" ]   
CMD [ "streamlit", "run", "streamlit_app.py"]   
