# curent collection of models

gpt-4o:
    provider: openai
    openai_api_base: https://free-cdo.openai.azure.com/openai/deployments/cod-free-gpt4o/chat/completions?api-version=2024-02-15-preview
    openai_api_version: 2024-02-15-preview
    openai_api_type: azure
    temperature: 0.2
claude3-haiku:
    provider: bedrock
    region_name: eu-central-1
    model_id: anthropic.claude-3-haiku-20240307-v1:0
    model_kwargs:
      temperature: 0.2
claude3-sonnet:
    provider: bedrock
    region_name: eu-central-1
    model_id: anthropic.claude-3-5-sonnet-20240620-v1:0
    model_kwargs:
      temperature: 0.2
mistral-large:
    provider: bedrock
    region_name: eu-west-3
    model_id: mistral.mistral-large-2402-v1:0
mistral-7b:
    provider: bedrock
    region_name: eu-west-3
    model_id: mistral.mistral-7b-instruct-v0:2
mixtral:
    provider: bedrock
    region_name: eu-west-3
    model_id: mistral.mixtral-8x7b-instruct-v0:1

